[build]
  # We are explicitly adding a build command to ensure NPM dependencies 
  # are installed before the functions are bundled.
  command = "npm install"
  publish = "/" 

[functions]
  directory = "netlify/functions"
  node_bundler = "zip"
